name: "Create and Upload PDF"
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_path: docs
          output_dir: pdfs
          build_html: false
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: zip --junk-paths Intensivregister-API-Dokumentation pdfs/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: Intensivregister-API-Dokumentation.zip
          asset_name: Intensivregister-API-Dokumentation
          tag: ${{ github.ref }}
          overwrite: true
          promote: true
          make_latest: true